In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plat
import seaborn as sns

In [17]:
tips = sns.load_dataset('tips')

In [18]:
type(tips)

pandas.DataFrame

In [19]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [20]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
estatisticas = tips.groupby('time')['tip'].mean()

In [25]:
estatisticas

time
Lunch     2.728088
Dinner    3.102670
Name: tip, dtype: float64

In [26]:
estatisticas = tips.groupby('time')['tip'].agg(['mean', 'median', 'std'])

In [27]:
estatisticas

            mean  median       std
time
Lunch   2.728088    2.25  1.205345
Dinner  3.102670    3.00  1.436243

In [28]:
estatbill = tips.groupby('time')['total_bill'].mean()

In [29]:
estatbill

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [45]:
def simulador_cassino(n_jogadores= 10, saldo_inicial=200):
    custo = 20
    premios = [0, 1, 1, 2, 20, 20, 20, 30, 60] 
    resultados = []
    
    for n in range(n_jogadores):
        jogadas = 0
        max_saldo = saldo_inicial
        saldo = saldo_inicial
    
        while saldo >= custo:
            ganho = np.random.choice(premios)
            saldo = saldo +ganho - custo
            jogadas += 1
    
            if saldo > max_saldo:
                max_saldo = saldo
        resultados.append({"jogador": n+1, "total_jogadas": jogadas, "saldo_maximo": max_saldo})
        print(f"jogador {n}: {jogadas}")
    return pd.DataFrame(resultados)

In [74]:
jogos = simulador_cassino()
jogos

jogador 0: 27
jogador 1: 143
jogador 2: 113
jogador 3: 65
jogador 4: 36
jogador 5: 32
jogador 6: 209
jogador 7: 15
jogador 8: 52
jogador 9: 45

   jogador  total_jogadas  saldo_maximo
0        1             27           200
1        2            143           257
2        3            113           226
3        4             65           213
4        5             36           240
5        6             32           240
6        7            209           334
7        8             15           200
8        9             52           277
9       10             45           200

In [75]:
medias10 = []
for i in range (1000):
    jogos = simulador_cassino(100)
    medias10.append(jogos['total_jogadas'].mean())

jogador 0: 40
jogador 1: 261
jogador 2: 129
jogador 3: 29
jogador 4: 52
jogador 5: 34
jogador 6: 83
jogador 7: 20
jogador 8: 112
jogador 9: 38
jogador 10: 100
jogador 11: 43
jogador 12: 117
jogador 13: 38
jogador 14: 15
jogador 15: 66
jogador 16: 54
jogador 17: 55
jogador 18: 12
jogador 19: 44
jogador 20: 110
jogador 21: 37
jogador 22: 52
jogador 23: 35
jogador 24: 170
jogador 25: 130
jogador 26: 129
jogador 27: 34
jogador 28: 181
jogador 29: 21
jogador 30: 53
jogador 31: 29
jogador 32: 86
jogador 33: 55
jogador 34: 30
jogador 35: 36
jogador 36: 199
jogador 37: 81
jogador 38: 66
jogador 39: 24
jogador 40: 54
jogador 41: 21
jogador 42: 33
jogador 43: 31
jogador 44: 65
jogador 45: 31
jogador 46: 74
jogador 47: 193
jogador 48: 32
jogador 49: 27
jogador 50: 141
jogador 51: 36
jogador 52: 74
jogador 53: 217
jogador 54: 56
jogador 55: 63
jogador 56: 159
jogador 57: 113
jogador 58: 105
jogador 59: 95
jogador 60: 63
jogador 61: 39
jogador 62: 146
jogador 63: 108
jogador 64: 34
jogador 65: 29
jogador 66: 91
jogador 67: 57
jogador 68: 39
jogador 69: 169
jogador 70: 82
jogador 71: 30
jogador 72: 16
jogador 73: 196
jogador 74: 101
jogador 75: 50
jogador 76: 24
jogador 77: 19
jogador 78: 75
jogador 79: 86
jogador 80: 105
jogador 81: 22
jogador 82: 54
jogador 83: 54
jogador 84: 57
jogador 85: 35
jogador 86: 47
jogador 87: 33
jogador 88: 32
jogador 89: 37
jogador 90: 42
jogador 91: 55
jogador 92: 56
jogador 93: 94
jogador 94: 99
jogador 95: 50
jogador 96: 16
jogador 97: 61
jogador 98: 203
jogador 99: 98
jogador 0: 49
jogador 1: 130
jogador 2: 48
jogador 3: 99
jogador 4: 31
jogador 5: 16
jogador 6: 26
jogador 7: 38
jogador 8: 135
jogador 9: 37
jogador 10: 70
jogador 11: 50
jogador 12: 30
jogador 13: 139
jogador 14: 46
jogador 15: 48
jogador 16: 46
jogador 17: 59
jogador 18: 81
jogador 19: 31
jogador 20: 18
jogador 21: 93
jogador 22: 49
jogador 23: 48
jogador 24: 54
jogador 25: 114
jogador 26: 32
jogador 27: 20
jogador 28: 130
jogador 29: 117
jogador 30: 35
jogador 31: 24
jogador 32: 30
jogador 33: 161
jogador 34: 190
jogador 35: 68
jogador 36: 35
jogador 37: 16
jogador 38: 53
jogador 39: 238
jogador 40: 38
jogador 41: 232
jogador 42: 92
jogador 43: 39
jogador 44: 72
jogador 45: 69
jogador 46: 132
jogador 47: 174
jogador 48: 24
jogador 49: 220
jogador 50: 124
jogador 51: 69
jogador 52: 65
jogador 53: 71
jogador 54: 27
jogador 55: 86
jogador 56: 57
jogador 57: 147
jogador 58: 22
jogador 59: 24
jogador 60: 43
jogador 61: 89
jogador 62: 16
jogador 63: 24
jogador 64: 177
jogador 65: 43
jogador 66: 19
jogador 67: 28
jogador 68: 71
jogador 69: 104
jogador 70: 67
jogador 71: 103
jogador 72: 214
jogador 73: 31
jogador 74: 81
jogador 75: 53
jogador 76: 28
jogador 77: 96
jogador 78: 17
jogador 79: 31
jogador 80: 22
jogador 81: 51
jogador 82: 90
jogador 83: 23
jogador 84: 183
jogador 85: 68
jogador 86: 35
jogador 87: 146
jogador 88: 247
jogador 89: 26
jogador 90: 48
jogador 91: 66
jogador 92: 21
jogador 93: 165
jogador 94: 22
jogador 95: 18
jogador 96: 106
jogador 97: 66
jogador 98: 33
jogador 99: 69
jogador 0: 115
jogador 1: 45
jogador 2: 55
jogador 3: 385
jogador 4: 95
jogador 5: 44
jogador 6: 39
jogador 7: 53
jogador 8: 28
jogador 9: 45
jogador 10: 35
jogador 11: 69
jogador 12: 20
jogador 13: 57
jogador 14: 22
jogador 15: 38
jogador 16: 45
jogador 17: 98
jogador 18: 121
jogador 19: 87
jogador 20: 106
jogador 21: 56
jogador 22: 40
jogador 23: 43
jogador 24: 326
jogador 25: 34
jogador 26: 158
jogador 27: 44
jogador 28: 121
jogador 29: 92
jogador 30: 113
jogador 31: 58
jogador 32: 60
jogador 33: 26
jogador 34: 109
jogador 35: 78
jogador 36: 144
jogador 37: 166
jogador 38: 17
jogador 39: 26
jogador 40: 126
jogador 41: 36
jogador 42: 126
jogador 43: 29
jogador 44: 33
jogador 45: 96
jogador 46: 47
jogador 47: 77
jogador 48: 71
jogador 49: 17
jogador 50: 105
jogador 51: 53
jogador 52: 28
jogador 53: 171
jogador 54: 96
jogador 55: 52
jogador 56: 17
jogador 57: 34
jogador 58: 31
jogador 59: 62
jogador 60: 52
jogador 61: 60
jogador 62: 82
jogador 63: 36
jogador 64: 49
jogador 65: 46
jogador 66: 191
jogador 67: 17
jogador 68: 35
jogador 69: 39
jogador 70: 30
jogador 71: 15
jogador 72: 126
jogador 73: 94
jogador 74: 238
jogador 75: 109
jogador 76: 86
jogador 77: 137
jogador 78: 28
jogador 79: 49
jogador 80: 84
jogador 81: 48
jogador 82: 366
jogador 83: 26
jogador 84: 60
jogador 85: 20
jogador 86: 48
jogador 87: 54
jogador 88: 79
jogador 89: 105
jogador 90: 52
jogador 91: 29
jogador 92: 23
jogador 93: 36
jogador 94: 49
jogador 95: 53
jogador 96: 29
jogador 97: 82
jogador 98: 68
jogador 99: 52
jogador 0: 31
jogador 1: 41
jogador 2: 31
jogador 3: 41
jogador 4: 54
jogador 5: 59
jogador 6: 20
jogador 7: 31
jogador 8: 114
jogador 9: 30
jogador 10: 34
jogador 11: 39
jogador 12: 79
jogador 13: 37
jogador 14: 19
jogador 15: 30
jogador 16: 41
jogador 17: 35
jogador 18: 110
jogador 19: 49
jogador 20: 37
jogador 21: 34
jogador 22: 62
jogador 23: 91
jogador 24: 29
jogador 25: 67
jogador 26: 100
jogador 27: 36
jogador 28: 24
jogador 29: 76
jogador 30: 15
jogador 31: 43
jogador 32: 32
jogador 33: 45
jogador 34: 77
jogador 35: 37
jogador 36: 98
jogador 37: 21
jogador 38: 20
jogador 39: 83
jogador 40: 88
jogador 41: 47
jogador 42: 78
jogador 43: 29
jogador 44: 28
jogador 45: 90
jogador 46: 56
jogador 47: 40
jogador 48: 33
jogador 49: 94
jogador 50: 112
jogador 51: 44
jogador 52: 38
jogador 53: 50
jogador 54: 38
jogador 55: 84
jogador 56: 69
jogador 57: 32
jogador 58: 59
jogador 59: 64
jogador 60: 70
jogador 61: 65
jogador 62: 89
jogador 63: 37
jogador 64: 21
jogador 65: 128
jogador 66: 78
jogador 67: 43
jogador 68: 62
jogador 69: 61
jogador 70: 17
jogador 71: 122
jogador 72: 131
jogador 73: 187
jogador 74: 33
jogador 75: 23
jogador 76: 18
jogador 77: 43
jogador 78: 38
jogador 79: 75
jogador 80: 58
jogador 81: 61
jogador 82: 25
jogador 83: 136
jogador 84: 101
jogador 85: 77
jogador 86: 22
jogador 87: 80
jogador 88: 31
jogador 89: 45
jogador 90: 38
jogador 91: 38
jogador 92: 134
jogador 93: 31
jogador 94: 134
jogador 95: 152
jogador 96: 21
jogador 97: 20
jogador 98: 31
jogador 99: 50
jogador 0: 104
jogador 1: 29
jogador 2: 24
jogador 3: 98
jogador 4: 41
jogador 5: 61
jogador 6: 33
jogador 7: 104
jogador 8: 161
jogador 9: 51
jogador 10: 37
jogador 11: 62
jogador 12: 61
jogador 13: 114
jogador 14: 24
jogador 15: 106
jogador 16: 82
jogador 17: 61
jogador 18: 23
jogador 19: 33
jogador 20: 54
jogador 21: 25
jogador 22: 87
jogador 23: 73
jogador 24: 79
jogador 25: 61
jogador 26: 268
jogador 27: 29
jogador 28: 39
jogador 29: 48
jogador 30: 113
jogador 31: 25
jogador 32: 42
jogador 33: 34
jogador 34: 30
jogador 35: 87
jogador 36: 39
jogador 37: 80
jogador 38: 18
jogador 39: 67
jogador 40: 199
jogador 41: 65
jogador 42: 64
jogador 43: 229
jogador 44: 41
jogador 45: 149
jogador 46: 65
jogador 47: 124
jogador 48: 27
jogador 49: 65
jogador 50: 47
jogador 51: 21
jogador 52: 22
jogador 53: 39
jogador 54: 45
jogador 55: 21
jogador 56: 99
jogador 57: 78
jogador 58: 41
jogador 59: 22
jogador 60: 164
jogador 61: 146
jogador 62: 45
jogador 63: 17
jogador 64: 75
jogador 65: 37
jogador 66: 167
jogador 67: 22
jogador 68: 103
jogador 69: 28
jogador 70: 138
jogador 71: 121
jogador 72: 56
jogador 73: 23
jogador 74: 65
jogador 75: 132
jogador 76: 83
jogador 77: 80
jogador 78: 79
jogador 79: 34
jogador 80: 181
jogador 81: 57
jogador 82: 34
jogador 83: 29
jogador 84: 78
jogador 85: 100
jogador 86: 53
jogador 87: 78
jogador 88: 24
jogador 89: 155
jogador 90: 55
jogador 91: 54
jogador 92: 42
jogador 93: 99
jogador 94: 43
jogador 95: 36
jogador 96: 60
jogador 97: 94
jogador 98: 180
jogador 99: 18
jogador 0: 87
jogador 1: 51
jogador 2: 42
jogador 3: 72
jogador 4: 28
jogador 5: 58
jogador 6: 150
jogador 7: 61
jogador 8: 40
jogador 9: 52
jogador 10: 56
jogador 11: 39
jogador 12: 49
jogador 13: 47
jogador 14: 34
jogador 15: 101
jogador 16: 30
jogador 17: 39
jogador 18: 70
jogador 19: 208
jogador 20: 56
jogador 21: 21
jogador 22: 28
jogador 23: 83
jogador 24: 38
jogador 25: 96
jogador 26: 219
jogador 27: 46
jogador 28: 12
jogador 29: 77
jogador 30: 38
jogador 31: 41
jogador 32: 28
jogador 33: 145
jogador 34: 79
jogador 35: 73
jogador 36: 142
jogador 37: 82
jogador 38: 90
jogador 39: 27
jogador 40: 40
jogador 41: 47
jogador 42: 46
jogador 43: 66
jogador 44: 27
jogador 45: 84
jogador 46: 20
jogador 47: 48
jogador 48: 20
jogador 49: 102
jogador 50: 22
jogador 51: 77
jogador 52: 60
jogador 53: 321
jogador 54: 50
jogador 55: 66
jogador 56: 121
jogador 57: 29
jogador 58: 51
jogador 59: 79
jogador 60: 50
jogador 61: 52
jogador 62: 47
jogador 63: 35
jogador 64: 57
jogador 65: 41
jogador 66: 23
jogador 67: 52
jogador 68: 38
jogador 69: 122
jogador 70: 40
jogador 71: 27
jogador 72: 136
jogador 73: 64
jogador 74: 59
jogador 75: 108
jogador 76: 20
jogador 77: 28
jogador 78: 44
jogador 79: 44
jogador 80: 97
jogador 81: 27
jogador 82: 80
jogador 83: 27
jogador 84: 109
jogador 85: 64
jogador 86: 39
jogador 87: 88
jogador 88: 25
jogador 89: 294
jogador 90: 16
jogador 91: 42
jogador 92: 117
jogador 93: 162
jogador 94: 53
jogador 95: 20
jogador 96: 21
jogador 97: 204
jogador 98: 46
jogador 99: 23
jogador 0: 31
jogador 1: 75
jogador 2: 91
jogador 3: 149
jogador 4: 176
jogador 5: 40
jogador 6: 84
jogador 7: 88
jogador 8: 64
jogador 9: 180
jogador 10: 54
jogador 11: 27
jogador 12: 189
jogador 13: 92
jogador 14: 26
jogador 15: 19
jogador 16: 49
jogador 17: 22
jogador 18: 122
jogador 19: 23
jogador 20: 29
jogador 21: 28
jogador 22: 94
jogador 23: 49
jogador 24: 16
jogador 25: 91
jogador 26: 45
jogador 27: 31
jogador 28: 61
jogador 29: 55
jogador 30: 24
jogador 31: 78
jogador 32: 23
jogador 33: 55
jogador 34: 21
jogador 35: 68
jogador 36: 64
jogador 37: 78
jogador 38: 55
jogador 39: 21
jogador 40: 35
jogador 41: 38
jogador 42: 86
jogador 43: 185
jogador 44: 50
jogador 45: 54
jogador 46: 96
jogador 47: 31
jogador 48: 32
jogador 49: 33
jogador 50: 93
jogador 51: 133
jogador 52: 87
jogador 53: 40
jogador 54: 66
jogador 55: 79
jogador 56: 31
jogador 57: 65
jogador 58: 44
jogador 59: 21
jogador 60: 29
jogador 61: 22
jogador 62: 12
jogador 63: 67
jogador 64: 146
jogador 65: 42
jogador 66: 35
jogador 67: 45
jogador 68: 76
jogador 69: 42
jogador 70: 62
jogador 71: 23
jogador 72: 28
jogador 73: 48
jogador 74: 52
jogador 75: 32
jogador 76: 63
jogador 77: 83
jogador 78: 21
jogador 79: 110
jogador 80: 118
jogador 81: 73
jogador 82: 13
jogador 83: 183
jogador 84: 40
jogador 85: 45
jogador 86: 25
jogador 87: 90
jogador 88: 155
jogador 89: 55
jogador 90: 77
jogador 91: 83
jogador 92: 103
jogador 93: 68
jogador 94: 30
jogador 95: 67
jogador 96: 32
jogador 97: 122
jogador 98: 44
jogador 99: 34
jogador 0: 40
jogador 1: 173
jogador 2: 47
jogador 3: 35
jogador 4: 43
jogador 5: 19
jogador 6: 52
jogador 7: 18
jogador 8: 20
jogador 9: 19
jogador 10: 55
jogador 11: 83
jogador 12: 44
jogador 13: 32
jogador 14: 47
jogador 15: 65
jogador 16: 67
jogador 17: 114
jogador 18: 99
jogador 19: 26
jogador 20: 24
jogador 21: 64
jogador 22: 98
jogador 23: 96
jogador 24: 40
jogador 25: 20
jogador 26: 83
jogador 27: 50
jogador 28: 33
jogador 29: 17
jogador 30: 23
jogador 31: 26
jogador 32: 54
jogador 33: 51
jogador 34: 54
jogador 35: 26
jogador 36: 34
jogador 37: 19
jogador 38: 54
jogador 39: 22
jogador 40: 19
jogador 41: 42
jogador 42: 140
jogador 43: 27
jogador 44: 64
jogador 45: 47
jogador 46: 143
jogador 47: 80
jogador 48: 127
jogador 49: 82
jogador 50: 18
jogador 51: 54
jogador 52: 46
jogador 53: 108
jogador 54: 41
jogador 55: 35
jogador 56: 30
jogador 57: 57
jogador 58: 62
jogador 59: 49
jogador 60: 17
jogador 61: 116
jogador 62: 18
jogador 63: 120
jogador 64: 29
jogador 65: 32
jogador 66: 36
jogador 67: 35
jogador 68: 55
jogador 69: 37
jogador 70: 20
jogador 71: 181
jogador 72: 33
jogador 73: 98
jogador 74: 40
jogador 75: 47
jogador 76: 24
jogador 77: 43
jogador 78: 38
jogador 79: 28
jogador 80: 61
jogador 81: 37
jogador 82: 116
jogador 83: 25
jogador 84: 62
jogador 85: 18
jogador 86: 53
jogador 87: 69
jogador 88: 61
jogador 89: 71
jogador 90: 145
jogador 91: 88
jogador 92: 135
jogador 93: 64
jogador 94: 85
jogador 95: 121
jogador 96: 48
jogador 97: 17
jogador 98: 28
jogador 99: 26
jogador 0: 86
jogador 1: 71
jogador 2: 46
jogador 3: 15
jogador 4: 98
jogador 5: 64
jogador 6: 35
jogador 7: 247
jogador 8: 109
jogador 9: 34
jogador 10: 22
jogador 11: 28
jogador 12: 55
jogador 13: 43
jogador 14: 87
jogador 15: 43
jogador 16: 44
jogador 17: 40
jogador 18: 115
jogador 19: 52
jogador 20: 168
jogador 21: 44
jogador 22: 141
jogador 23: 75
jogador 24: 63
jogador 25: 46
jogador 26: 16
jogador 27: 82
jogador 28: 77
jogador 29: 33
jogador 30: 177
jogador 31: 101
jogador 32: 80
jogador 33: 96
jogador 34: 11
jogador 35: 35
jogador 36: 70
jogador 37: 38
jogador 38: 259
jogador 39: 252
jogador 40: 149
jogador 41: 40
jogador 42: 59
jogador 43: 69
jogador 44: 20
jogador 45: 32
jogador 46: 28
jogador 47: 80
jogador 48: 31
jogador 49: 77
jogador 50: 57
jogador 51: 34
jogador 52: 41
jogador 53: 47
jogador 54: 16
jogador 55: 118
jogador 56: 60
jogador 57: 18
jogador 58: 58
jogador 59: 55
jogador 60: 232
jogador 61: 147
jogador 62: 52
jogador 63: 43
jogador 64: 84
jogador 65: 147
jogador 66: 58
jogador 67: 74
jogador 68: 79
jogador 69: 144
jogador 70: 59
jogador 71: 46
jogador 72: 97
jogador 73: 83
jogador 74: 41
jogador 75: 27
jogador 76: 44
jogador 77: 53
jogador 78: 28
jogador 79: 38
jogador 80: 54
jogador 81: 32
jogador 82: 32
jogador 83: 29
jogador 84: 35
jogador 85: 29
jogador 86: 36
jogador 87: 53
jogador 88: 82
jogador 89: 61
jogador 90: 97
jogador 91: 23
jogador 92: 63
jogador 93: 165
jogador 94: 29
jogador 95: 14
jogador 96: 20
jogador 97: 110
jogador 98: 85
jogador 99: 95
jogador 0: 19
jogador 1: 86
jogador 2: 342
jogador 3: 36
jogador 4: 55
jogador 5: 40
jogador 6: 64
jogador 7: 72
jogador 8: 65
jogador 9: 39
jogador 10: 59
jogador 11: 82
jogador 12: 355
jogador 13: 127
jogador 14: 42
jogador 15: 27
jogador 16: 35
jogador 17: 65
jogador 18: 146
jogador 19: 45
jogador 20: 33
jogador 21: 59
jogador 22: 36
jogador 23: 40
jogador 24: 32
jogador 25: 90
jogador 26: 98
jogador 27: 17
jogador 28: 61
jogador 29: 135
jogador 30: 23
jogador 31: 32
jogador 32: 149
jogador 33: 141
jogador 34: 157
jogador 35: 128
jogador 36: 41
jogador 37: 16
jogador 38: 58
jogador 39: 37
jogador 40: 41
jogador 41: 36
jogador 42: 25
jogador 43: 48
jogador 44: 209
jogador 45: 17
jogador 46: 33
jogador 47: 42
jogador 48: 19
jogador 49: 40
jogador 50: 20
jogador 51: 43
jogador 52: 38
jogador 53: 60
jogador 54: 27
jogador 55: 92
jogador 56: 19
jogador 57: 138
jogador 58: 44
jogador 59: 51
jogador 60: 17
jogador 61: 54
jogador 62: 82
jogador 63: 43
jogador 64: 19
jogador 65: 232
jogador 66: 120
jogador 67: 36
jogador 68: 106
jogador 69: 49
jogador 70: 24
jogador 71: 323
jogador 72: 130
jogador 73: 136
jogador 74: 52
jogador 75: 17
jogador 76: 127
jogador 77: 26
jogador 78: 102
jogador 79: 32
jogador 80: 104
jogador 81: 39
jogador 82: 30
jogador 83: 36
jogador 84: 31
jogador 85: 44
jogador 86: 20
jogador 87: 81
jogador 88: 61
jogador 89: 42
jogador 90: 49
jogador 91: 39
jogador 92: 47
jogador 93: 26
jogador 94: 15
jogador 95: 59
jogador 96: 170
jogador 97: 23
jogador 98: 41
jogador 99: 101
jogador 0: 57
jogador 1: 28
jogador 2: 58
jogador 3: 53
jogador 4: 109
jogador 5: 35
jogador 6: 59
jogador 7: 39
jogador 8: 25
jogador 9: 27
jogador 10: 32
jogador 11: 64
jogador 12: 37
jogador 13: 54
jogador 14: 24
jogador 15: 220
jogador 16: 25
jogador 17: 191
jogador 18: 16
jogador 19: 82
jogador 20: 26
jogador 21: 31
jogador 22: 31
jogador 23: 18
jogador 24: 47
jogador 25: 34
jogador 26: 12
jogador 27: 30
jogador 28: 84
jogador 29: 112
jogador 30: 20
jogador 31: 86
jogador 32: 29
jogador 33: 19
jogador 34: 50
jogador 35: 35
jogador 36: 28
jogador 37: 99
jogador 38: 49
jogador 39: 94
jogador 40: 18
jogador 41: 27
jogador 42: 42
jogador 43: 22
jogador 44: 43
jogador 45: 23
jogador 46: 90
jogador 47: 41
jogador 48: 130
jogador 49: 41
jogador 50: 29
jogador 51: 35
jogador 52: 60
jogador 53: 38
jogador 54: 381
jogador 55: 72
jogador 56: 29
jogador 57: 84
jogador 58: 97
jogador 59: 44
jogador 60: 17
jogador 61: 51
jogador 62: 27
jogador 63: 46
jogador 64: 22
jogador 65: 21
jogador 66: 64
jogador 67: 32
jogador 68: 79
jogador 69: 43
jogador 70: 42
jogador 71: 35
jogador 72: 232
jogador 73: 26
jogador 74: 47
jogador 75: 92
jogador 76: 41
jogador 77: 57
jogador 78: 87
jogador 79: 27
jogador 80: 122
jogador 81: 31
jogador 82: 25
jogador 83: 43
jogador 84: 89
jogador 85: 13
jogador 86: 30
jogador 87: 64
jogador 88: 56
jogador 89: 44
jogador 90: 81
jogador 91: 34
jogador 92: 48
jogador 93: 25
jogador 94: 48
jogador 95: 20
jogador 96: 167
jogador 97: 40
jogador 98: 24
jogador 99: 83
jogador 0: 36
jogador 1: 56
jogador 2: 18
jogador 3: 17
jogador 4: 37
jogador 5: 69
jogador 6: 109
jogador 7: 45
jogador 8: 42
jogador 9: 36
jogador 10: 70
jogador 11: 25
jogador 12: 59
jogador 13: 13
jogador 14: 26
jogador 15: 158
jogador 16: 27
jogador 17: 124
jogador 18: 23
jogador 19: 98
jogador 20: 29
jogador 21: 53
jogador 22: 32
jogador 23: 54
jogador 24: 56
jogador 25: 68
jogador 26: 156
jogador 27: 42
jogador 28: 71
jogador 29: 337
jogador 30: 74
jogador 31: 96
jogador 32: 16
jogador 33: 145
jogador 34: 46
jogador 35: 22
jogador 36: 145
jogador 37: 17
jogador 38: 142
jogador 39: 68
jogador 40: 46
jogador 41: 52
jogador 42: 35
jogador 43: 48
jogador 44: 43
jogador 45: 32
jogador 46: 210
jogador 47: 77
jogador 48: 85
jogador 49: 20
jogador 50: 104
jogador 51: 122
jogador 52: 66
jogador 53: 74
jogador 54: 95
jogador 55: 98
jogador 56: 136
jogador 57: 195
jogador 58: 162
jogador 59: 16
jogador 60: 127
jogador 61: 73
jogador 62: 67
jogador 63: 32
jogador 64: 54
jogador 65: 24
jogador 66: 112
jogador 67: 246
jogador 68: 72
jogador 69: 44
jogador 70: 54
jogador 71: 121
jogador 72: 129
jogador 73: 60
jogador 74: 103
jogador 75: 37
jogador 76: 37
jogador 77: 39
jogador 78: 65
jogador 79: 35
jogador 80: 79
jogador 81: 61
jogador 82: 82
jogador 83: 72
jogador 84: 20
jogador 85: 50
jogador 86: 85
jogador 87: 86
jogador 88: 20
jogador 89: 58
jogador 90: 25
jogador 91: 75
jogador 92: 53
jogador 93: 28
jogador 94: 87
jogador 95: 66
jogador 96: 23
jogador 97: 27
jogador 98: 62
jogador 99: 89
jogador 0: 25
jogador 1: 38
jogador 2: 26
jogador 3: 20
jogador 4: 48
jogador 5: 72
jogador 6: 39
jogador 7: 19
jogador 8: 40
jogador 9: 54
jogador 10: 89
jogador 11: 16
jogador 12: 103
jogador 13: 25
jogador 14: 73
jogador 15: 78
jogador 16: 34
jogador 17: 57
jogador 18: 124
jogador 19: 27
jogador 20: 65
jogador 21: 126
jogador 22: 58
jogador 23: 58
jogador 24: 45
jogador 25: 111
jogador 26: 36
jogador 27: 34
jogador 28: 25
jogador 29: 61
jogador 30: 118
jogador 31: 65
jogador 32: 40
jogador 33: 151
jogador 34: 73
jogador 35: 15
jogador 36: 143
jogador 37: 20
jogador 38: 37
jogador 39: 46
jogador 40: 32
jogador 41: 224
jogador 42: 19
jogador 43: 62
jogador 44: 34
jogador 45: 110
jogador 46: 58
jogador 47: 75
jogador 48: 59
jogador 49: 64
jogador 50: 117
jogador 51: 24
jogador 52: 16
jogador 53: 67
jogador 54: 17
jogador 55: 24
jogador 56: 83
jogador 57: 33
jogador 58: 68
jogador 59: 42
jogador 60: 33
jogador 61: 122
jogador 62: 102
jogador 63: 86
jogador 64: 26
jogador 65: 67
jogador 66: 24
jogador 67: 74
jogador 68: 69
jogador 69: 48
jogador 70: 76
jogador 71: 29
jogador 72: 52
jogador 73: 220
jogador 74: 77
jogador 75: 76
jogador 76: 107
jogador 77: 103
jogador 78: 25
jogador 79: 93
jogador 80: 39
jogador 81: 46
jogador 82: 61
jogador 83: 36
jogador 84: 76
jogador 85: 89
jogador 86: 28
jogador 87: 95
jogador 88: 51
jogador 89: 16
jogador 90: 207
jogador 91: 27
jogador 92: 30
jogador 93: 64
jogador 94: 19
jogador 95: 38
jogador 96: 38
jogador 97: 48
jogador 98: 16
jogador 99: 60
jogador 0: 21
jogador 1: 69
jogador 2: 23
jogador 3: 34
jogador 4: 25
jogador 5: 27
jogador 6: 42
jogador 7: 61
jogador 8: 105
jogador 9: 26
jogador 10: 88
jogador 11: 513
jogador 12: 103
jogador 13: 16
jogador 14: 73
jogador 15: 32
jogador 16: 40
jogador 17: 103
jogador 18: 18
jogador 19: 56
jogador 20: 27
jogador 21: 82
jogador 22: 122
jogador 23: 75
jogador 24: 243
jogador 25: 78

In [ ]:
md10 = np
medias10 = [++]
for i in range (1000):
    jogos = simulador_cassino(100)
    medias10.append(jogos['total_jogadas'].mean())