In [1]:
from collections import Counter

In [2]:
def calcmedia(X):
    somatorio=0

    for x in X:
        somatorio=somatorio+x

    n=len(X)

    media = somatorio/n

    return media

In [3]:
Y=[1, 2, 3, 2, 6, 53, 5,3, 553, 43,7]
print( calcmedia(Y) )

61.63636363636363

In [4]:
import numpy as np

In [5]:
dados = np.random.normal( loc=40, scale=10, size=40000000).tolist()

In [6]:
print(calcmedia(dados))

39.99985031295399

In [7]:
import time

In [8]:
size=100000000
dados = np.random.normal( loc=40, scale=10, size=size)
start_time = time.time()
calcmedia(dados)
end_time = time.time()

print(end_time-start_time)

13.060395956039429

In [9]:
def calcmediana(X):
  X = np.sort(X)

  n= X.size

# X[0] x[1] x[2] x[3] x[4] -> n=5
# X[0] x[1] x[2] x[3]  -> n=4

  if n%2==1:
    return X[ n//2 ]

  return (X[n//2]+X[n//2 - 1])/2

  # n*n   ex bubblesort
  # n*log(n)   ex quicksort

  # 10*10 =100
  # 10*log2(10)  10*3.5 = 35

  # 10^6 * 10^6 = 10^12
  # 10^6 * log2(10^6) = 2*10^7

In [10]:
Y = [4, 5, 7,  1, 9, 10]

print(calcmediana(Y))

6.0

In [11]:
def calcmoda(X):
  contagem = Counter(X)
  return contagem.most_common(1)[0][0]

In [12]:
Y = ["4", "5", 7,  1, 3.0, int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3),int(3), 9, 10, "4", "5","4", "3", "3", "3", "3", 7, 2, 2, 5,3, 3, 3, 3, 3, 3, 3]

calcmoda(Y)

3.0

In [13]:
salario=[2000, 2000, 2400, 2500, 3000 , 5000000]

In [14]:
calcmedia(salario)

835316.6666666666

In [15]:
calcmediana(salario)

np.float64(2450.0)

In [16]:
ngols=[0,1,2,0,0,0,1,1,2]

In [17]:
calcmediana(ngols)

np.int64(1)

In [18]:
calcmoda(ngols)

0

In [19]:
calcmedia(ngols)

0.7777777777777778

In [20]:
jogo = [ 0 , 1 , 1, 2 , 20, 20, 20, 20,30, 60]

In [21]:
calcmedia(jogo)

17.4

In [22]:
import pandas as pd

In [23]:
url = "https://agdaf.com/estatistica/campeonato-brasileiro-full.csv"
df = pd.read_csv(url)

In [24]:
df.columns

Index(['ID', 'rodata', 'data', 'hora', 'mandante', 'visitante',
       'formacao_mandante', 'formacao_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'vencedor', 'arena', 'mandante_Placar',
       'visitante_Placar', 'mandante_Estado', 'visitante_Estado'],
      dtype='object')

In [25]:
df.tail(20)

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
8765,8766,37,03/12/2024,20:04,Corinthians,Bahia,4-3-1-2,3-4-1-2,R. Díaz,R. Ceni,Corinthians,Neo Química Arena,3,0,SP,BA
8766,8767,37,04/12/2024,19:02,Vasco,Atletico-MG,4-1-2-1-2,3-4-3,F. Loureiro,G. Milito,Vasco,Estádio São Januário,2,0,RJ,MG
8767,8768,37,04/12/2024,20:01,Vitoria,Gremio,5-3-2,4-2-3-1,T. Carpini Barbosa,Renato Gaúcho,-,Barradão,1,1,BA,RS
8768,8769,37,04/12/2024,20:03,Criciuma,Flamengo,4-3-1-2,4-2-3-1,C. Tencati,F. Luís,Flamengo,Estádio Heriberto Hülse,0,3,SC,RJ
8769,8770,37,04/12/2024,20:04,Sao Paulo,Juventude,4-2-3-1,4-2-3-1,L. Zubeldía,F. Matias,Juventude,MorumBIS,1,2,SP,RS
8770,8771,37,04/12/2024,21:30,Atletico-GO,Fortaleza,4-2-3-1,4-2-3-1,A. Gomes,J. Vojvoda,Atletico-GO,Estádio Antônio Accioly - Atlético Goianiense,3,1,GO,CE
8771,8772,37,04/12/2024,21:30,Internacional,Botafogo-RJ,4-2-2-2,4-2-3-1,R. Machado Marques,A. Torres Gomes Araújo Amorim,Botafogo-RJ,Estádio Beira-Rio,0,1,RS,RJ
8772,8773,37,04/12/2024,21:30,Cruzeiro,Palmeiras,4-3-2-1,4-2-3-1,F. Diniz Silva,A. Moreira Ferreira,Palmeiras,Mineirão,1,2,MG,SP
8773,8775,37,05/12/2024,20:00,Athletico-PR,Bragantino,4-2-3-1,4-2-3-1,L. González,F. Seabra,Bragantino,Ligga Arena,1,2,PR,SP
8774,8774,37,05/12/2024,20:01,Fluminense,Cuiaba,4-2-3-1,4-2-3-1,L. Venker de Menezes,B. Franco,Fluminense,Maracanã,1,0,RJ,MT
8775,8777,38,08/12/2024,16:04,Juventude,Cruzeiro,4-2-3-1,4-2-3-1,F. Matias,F. Diniz Silva,Cruzeiro,Alfredo Jaconi,0,1,RS,MG
8776,8778,38,08/12/2024,16:04,Bahia,Atletico-GO,4-2-3-1,4-1-4-1,R. Ceni,A. Gomes,Bahia,Arena Fonte Nova,2,0,BA,GO
8777,8779,38,08/12/2024,16:04,Flamengo,Vitoria,4-4-2,4-3-3,F. Luís,T. Carpini Barbosa,-,Maracanã,2,2,RJ,BA
8778,8781,38,08/12/2024,16:04,Atletico-MG,Athletico-PR,4-3-3,4-3-2-1,L. Gonçalves,L. González,Atletico-MG,Arena MRV,1,0,MG,PR
8779,8782,38,08/12/2024,16:04,Botafogo-RJ,Sao Paulo,NaN,NaN,A. Torres Gomes Araújo Amorim,L. Zubeldía,Botafogo-RJ,Estádio Nilton Santos,2,1,RJ,SP
8780,8783,38,08/12/2024,16:04,Cuiaba,Vasco,4-3-3,4-3-2-1,B. Franco,F. Loureiro,Vasco,Arena Pantanal,1,2,MT,RJ
8781,8784,38,08/12/2024,16:04,Palmeiras,Fluminense,4-2-3-1,4-2-3-1,A. Moreira Ferreira,L. Venker de Menezes,Fluminense,Allianz Parque,0,1,SP,RJ
8782,8776,38,08/12/2024,16:05,Fortaleza,Internacional,4-2-3-1,4-1-2-1-2,J. Vojvoda,R. Machado Marques,Fortaleza,Arena Castelão,3,0,CE,RS
8783,8780,38,08/12/2024,16:05,Bragantino,Criciuma,4-2-3-1,4-1-2-1-2,F. Seabra,C. Tencati,Bragantino,Nabizão,5,1,SP,SC
8784,8785,38,08/12/2024,16:05,Gremio,Corinthians,4-4-2,4-3-1-2,Renato Gaúcho,R. Díaz,Corinthians,Arena do Grêmio,0,3,RS,SP

In [26]:
timef = "Sport"
colcasa = "mandante"
colfora = "visitante"

gec = "mandante_Placar"
gfc = "visitante_Placar"

mask_casa = df[colcasa]==timef
mask_fora = df[colfora]==timef


dft= df[mask_casa | mask_fora]

gols= np.where(mask_casa[mask_casa|mask_fora])

In [27]:
mask_casa[mask_casa|mask_fora]

1955     True
1965    False
1971    False
1982     True
1990    False
        ...
7592     True
7610    False
7622     True
7634    False
7635     True
Name: mandante, Length: 418, dtype: bool

In [28]:
dft

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
1955,1956,1,13/05/2007,18:10,Sport,Santos,NaN,NaN,NaN,NaN,Sport,Ilha do Retiro,4,1,PE,SP
1965,1966,2,20/05/2007,18:10,Vasco,Sport,NaN,NaN,NaN,NaN,Vasco,São Januário,3,1,RJ,PE
1971,1972,3,27/05/2007,16:00,Gremio,Sport,NaN,NaN,NaN,NaN,Gremio,Olímpico,1,0,RS,PE
1982,1983,4,03/06/2007,16:00,Sport,Flamengo,NaN,NaN,NaN,NaN,-,Ilha do Retiro,2,2,PE,RJ
1990,1991,5,10/06/2007,16:00,Fluminense,Sport,NaN,NaN,NaN,NaN,Fluminense,Maracanã,3,0,RJ,PE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7592,7605,33,18/11/2021,20:59,Sport,Bahia,4-3-3,4-2-3-1,G. Florentín,A. Ferreira,Sport,Arena de Pernambuco,1,0,PE,BA
7610,7618,36,27/11/2021,21:30,Sao Paulo,Sport,4-4-2,4-3-3,R. Ceni,G. Florentín,Sao Paulo,Morumbi,2,0,SP,PE
7622,7615,35,03/12/2021,20:00,Sport,Flamengo,4-2-3-1,4-2-2-2,G. Florentín,M. Souza,-,Arena de Pernambuco,1,1,PE,RJ
7634,7635,37,06/12/2021,21:00,Chapecoense,Sport,4-4-2,4-2-3-1,F. Paiva Endres,G. Florentín,Sport,Arena Condá,0,1,SC,PE
7635,7642,38,09/12/2021,21:30,Sport,Athletico-PR,4-2-3-1,3-4-2-1,G. Florentín,J. Freitas,-,Arena de Pernambuco,1,1,PE,PR